### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by strarsis** [gre/kenburns#3]
It would be great if a LICENSE file is added to this project.
(Including [kenburns-canvas2d](https://github.com/gre/kenburns-canvas2d), [kenburns-webgl](https://github.com/gre/kenburns-webgl), [kenburns-dom](https://github.com/gre/kenburns-dom), [kenburns-editor](https://github.com/gre/kenburns-editor), [kenburns-core](https://github.com/gre/kenburns-core)).

**Comment by gre** [comment]
done :) thanks for reminder. the license didn't changed ( as it was already described in package.json ) but there are now LICENSE files.
