### ISSUE TITLE
README inconsistency?

### ISSUE THREAD

**Issue by strarsis** [gre/kenburns#5]
First example in README:
```js
var boundFunction1 = KenBurns.crop(1.0, [0.5, 0.5]);
var boundFunction2 = KenBurns.crop(0.2, [0.8, 0.5]);
````
    The first parameter is the zoom ratio. (this zoom ratio must be in ]0.0, 1.0] range) For instance, 1.0 display the full image size, 0.01 display a very tiny part of the image.
    The second parameter is the center of the effect (the [w,h] components are in percentage from 0.0 to 1.0). This parameter is optional, if not provided, the center is used.

Second example in README:
 ```js
kenBurns.run(img, KenBurns.crop([0.8, 0.5], 0.2), KenBurns.crop([0.5, 0.5], 1.0), 4000);
 ````
In the second example the center of effect is the first parameter and 
zoom ratio the second in contrast to the first example.

**Comment by gre** [comment]
I've released a major version of the library (2.0.0) that have a new documentation. https://github.com/gre/kenburns/blob/master/API.md

checkout also the example: https://github.com/gre/kenburns/blob/master/example/index.js

basically `crop` should be imported from the library `rect-crop` and yeah, the README was wrong order.
