### ISSUE TITLE
Play backwards

### ISSUE THREAD

**Issue by strarsis** [gre/kenburns#7]
For some effects/use cases it would be great if this module also 
allows playing backwards (either automatically or each frame). 
Alternatively a frame index/counter which can be incremented/changed and passed.

Edit: Would a "negative" easing be the right approach (https://github.com/gre/kenburns/blob/master/API.md)?

**Comment by gre** [comment]
For that, I would suggest you use the lower level API (`animateStep`), not the promise one (`animate`).

animate is just an helper to call animateStep many times.

when you run `animate(source, from, to, duration, easing)` it will call `animateStep(source, from, to, progress)` by varying progress from 0 to 1.
e.g.:

```
animate(source, from, to, 2000)
```

```
animateStep(source, from, to, 0)
animateStep(source, from, to, 0.01)
...
animateStep(source, from, to, 0.98)
animateStep(source, from, to, 0.99)
animateStep(source, from, to, 1) // after 2000 millis
```

see animate code:  https://github.com/gre/kenburns/blob/master/src/Base.js#L75-L89

you can inspire from it to do a backwards.

Also, i'm pretty sure you can workaround the easing to do this: `p => 1-p` and it will do backwards, but also if you want more control, just make your own version of that render loop.
